modLoader="javafml" #mandatory
loaderVersion="[28.1]" #mandatory. 26 for 1.14.2, 27 for 1.14.3
credits="Thanks to all the supporters!" #optional
[[mods]] #mandatory
modId="phycology" #mandatory
version="0.0.1" #mandatory
displayName="Phycology" #mandatory
description='''
A mod developed for broadening skills
'''